//! Cross-compile the `riscv-tests` ISA suite against the EBREAK `snake` env and
//! generate one `#[test]` per ELF for `tests/riscv_tests.rs`.
//!
//! The upstream test *bodies* (`riscv-tests/isa/rv32ui/*.S`) are unmodified; the
//! pass/fail convention is injected by `riscv-test-env/snake` (EBREAK with the
//! exit code in `a0`, no spike-style `tohost` polling). See the project README.
//!
//! Everything is best-effort: if the RISC-V toolchain or the submodules are
//! absent, the build still succeeds — an empty generated file is written and the
//! harness reports zero tests. A single test that fails to *compile* is skipped
//! with a `cargo:warning` rather than breaking the whole build.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// RV32I user-mode base-integer tests. The full set is 42 `.S` files; two are
/// excluded for ISA-scope reasons matching the Oracle ISS:
///   - `fence_i` — Zifencei, outside RV32I_Zicsr.
///   - `ma_data` — misaligned data access; the ISS halts (exit 132/133) rather
///     than trapping, so the test's trap-based recovery cannot complete.
const RV32UI: &[&str] = &[
    "add", "addi", "and", "andi", "auipc", "beq", "bge", "bgeu", "blt", "bltu", "bne", "jal",
    "jalr", "lb", "lbu", "ld_st", "lh", "lhu", "lui", "lw", "or", "ori", "sb", "sh", "simple",
    "sll", "slli", "slt", "slti", "sltiu", "sltu", "sra", "srai", "srl", "srli", "st_ld", "sub",
    "sw", "xor", "xori",
];

/// RV32 M-mode privileged tests that do not rely on non-ECALL synchronous-trap
/// delivery (the only sync cause the ISS implements is ECALL).
const RV32MI: &[&str] = &["csr", "scall", "mcsr"];

const GCC_FLAGS: &[&str] = &[
    "-march=rv32i_zicsr",
    "-mabi=ilp32",
    "-mcmodel=medany",
    "-static",
    "-nostdlib",
    "-nostartfiles",
    "-fno-builtin",
    "-fvisibility=hidden",
];

/// The Eos `bin/` demos that are self-checking and non-interactive, so they can
/// run unattended on the ISS. `echo_timer` is deliberately excluded — it blocks
/// on UART RX (`getchar`) and would never halt without an input source.
const EOS_DEMOS: &[&str] = &["sorts", "sieve", "numerics", "hanoi", "floyd", "crc32"];

/// Input-driven Eos demos: built like the rest, but they consume UART RX and so
/// need a scripted byte source rather than a bare run. They are driven by
/// hand-written tests in `tests/eos_demos.rs` (which locate the ELF and feed a
/// fixed input), not by the auto-generated no-input cases below.
const EOS_INPUT_DEMOS: &[&str] = &["snake", "snake_rt"];

/// The Rust target the Eos runtime is built for (see `Eos/.cargo/config.toml`).
const EOS_TARGET: &str = "riscv32i-unknown-none-elf";

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let gen_path = out_dir.join("riscv_tests_generated.rs");

    build_eos_demos(&manifest, &out_dir);

    let rvtests = manifest.join("riscv-tests");
    // The env lives in the riscv-tests fork's own `env` submodule
    // (SandToSystem/riscv-test-env), which carries our `snake/` shim.
    let env_dir = rvtests.join("env");
    let snake = env_dir.join("snake");
    let macros = rvtests.join("isa/macros/scalar");

    println!("cargo:rerun-if-changed=build.rs");
    println!(
        "cargo:rerun-if-changed={}",
        snake.join("riscv_test.h").display()
    );
    println!("cargo:rerun-if-changed={}", snake.join("link.ld").display());

    let submodules_ready =
        rvtests.join("isa/rv32ui/add.S").exists() && snake.join("riscv_test.h").exists();
    let gcc = find_gcc();

    if gcc.is_none() || !submodules_ready {
        let reason = if gcc.is_none() {
            "RISC-V toolchain (riscv64-unknown-elf-gcc) not found on PATH or /opt/riscv/bin"
        } else {
            "riscv-tests / riscv-test-env submodules not initialised"
        };
        println!("cargo:warning=riscv-tests harness disabled: {reason}");
        fs::write(
            &gen_path,
            format!("// riscv-tests harness disabled: {reason}\n"),
        )
        .unwrap();
        return;
    }
    let gcc = gcc.unwrap();

    let elf_dir = out_dir.join("riscv-tests");
    fs::create_dir_all(&elf_dir).unwrap();

    let includes = [
        format!("-I{}", snake.display()),
        format!("-I{}", macros.display()),
        format!("-I{}", env_dir.display()),
        format!("-T{}", snake.join("link.ld").display()),
    ];

    let mut generated =
        String::from("// @generated by build.rs — one #[test] per riscv-tests ELF.\n");
    let mut built = 0u32;

    for (group, list) in [("rv32ui", RV32UI), ("rv32mi", RV32MI)] {
        for name in list {
            let src = rvtests.join(format!("isa/{group}/{name}.S"));
            if !src.exists() {
                println!(
                    "cargo:warning=riscv-tests: missing source {}",
                    src.display()
                );
                continue;
            }
            println!("cargo:rerun-if-changed={}", src.display());

            let elf = elf_dir.join(format!("{group}-p-{name}"));
            let out = Command::new(&gcc)
                .args(GCC_FLAGS)
                .args(&includes)
                .arg(&src)
                .arg("-o")
                .arg(&elf)
                .output()
                .expect("failed to spawn RISC-V gcc");

            if !out.status.success() {
                println!(
                    "cargo:warning=riscv-tests: {group}-p-{name} failed to compile: {}",
                    String::from_utf8_lossy(&out.stderr).trim()
                );
                continue;
            }

            generated.push_str(&format!(
                "#[test]\nfn {group}_p_{name}() {{ run_one(r\"{}\", \"{group}-p-{name}\"); }}\n",
                elf.display()
            ));
            built += 1;
        }
    }

    fs::write(&gen_path, generated).unwrap();
    println!("cargo:warning=riscv-tests: compiled {built} test ELFs");
}

/// Build the Eos demo binaries and generate one `#[test]` per demo for
/// `tests/eos_demos.rs`, each loading the ELF onto a full Snake SoC and
/// asserting a clean halt.
///
/// Best-effort, mirroring the riscv-tests path: if the `Eos/` submodule is
/// missing or the cross-build fails (e.g. the `riscv32i-unknown-none-elf`
/// rustc target is not installed), an explanatory skip file is written and the
/// harness reports zero tests rather than breaking the build.
fn build_eos_demos(manifest: &Path, out_dir: &Path) {
    let gen_path = out_dir.join("eos_demos_generated.rs");
    let eos = manifest.join("Eos");

    println!("cargo:rerun-if-changed={}", eos.join("bin").display());
    println!("cargo:rerun-if-changed={}", eos.join("src").display());
    println!(
        "cargo:rerun-if-changed={}",
        eos.join("Cargo.toml").display()
    );
    println!("cargo:rerun-if-changed={}", eos.join("link.ld").display());

    if !eos.join("Cargo.toml").exists() {
        let reason = "Eos submodule not initialised";
        println!("cargo:warning=Eos demos disabled: {reason}");
        fs::write(&gen_path, format!("// Eos demos disabled: {reason}\n")).unwrap();
        return;
    }

    // Use the same cargo that is driving this build. The nested invocation runs
    // with `Eos/` as the working directory so Eos's own `.cargo/config.toml`
    // (target + linker script) is picked up; Eos has no external dependencies,
    // so this touches neither the registry nor the parent's target lock.
    let cargo = env::var("CARGO").unwrap_or_else(|_| "cargo".to_string());
    let mut cmd = Command::new(&cargo);
    cmd.current_dir(&eos).args(["build", "--release"]);
    for demo in EOS_DEMOS.iter().chain(EOS_INPUT_DEMOS) {
        cmd.args(["--bin", demo]);
    }
    // Strip the parent build's injected flags so they don't clobber Eos's
    // `.cargo/config.toml` rustflags (the `-Tlink.ld` link arg in particular)
    // or redirect its target directory.
    for var in [
        "CARGO_ENCODED_RUSTFLAGS",
        "RUSTFLAGS",
        "CARGO_BUILD_RUSTFLAGS",
        "CARGO_BUILD_TARGET",
        "CARGO_TARGET_DIR",
        "RUSTC",
        "RUSTC_WRAPPER",
        "RUSTC_WORKSPACE_WRAPPER",
    ] {
        cmd.env_remove(var);
    }

    match cmd.output() {
        Ok(out) if out.status.success() => {}
        Ok(out) => {
            let reason = format!(
                "cross-build failed (is the {EOS_TARGET} target installed? `rustup target add {EOS_TARGET}`)"
            );
            println!("cargo:warning=Eos demos disabled: {reason}");
            println!(
                "cargo:warning=Eos build stderr: {}",
                String::from_utf8_lossy(&out.stderr).trim()
            );
            fs::write(&gen_path, format!("// Eos demos disabled: {reason}\n")).unwrap();
            return;
        }
        Err(e) => {
            let reason = format!("could not spawn cargo for the Eos build: {e}");
            println!("cargo:warning=Eos demos disabled: {reason}");
            fs::write(&gen_path, format!("// Eos demos disabled: {reason}\n")).unwrap();
            return;
        }
    }

    let release = eos.join("target").join(EOS_TARGET).join("release");
    let mut generated = String::from("// @generated by build.rs — one #[test] per Eos demo ELF.\n");
    let mut built = 0u32;
    for demo in EOS_DEMOS {
        let elf = release.join(demo);
        if !elf.exists() {
            println!(
                "cargo:warning=Eos demos: expected ELF missing: {}",
                elf.display()
            );
            continue;
        }
        generated.push_str(&format!(
            "#[test]\nfn eos_{demo}() {{ run_demo(r\"{}\", \"{demo}\"); }}\n",
            elf.display()
        ));
        built += 1;
    }

    fs::write(&gen_path, generated).unwrap();
    println!("cargo:warning=Eos demos: built {built} demo ELFs");
}

/// Locate a RISC-V cross compiler: PATH first, then the common `/opt/riscv/bin`.
fn find_gcc() -> Option<PathBuf> {
    for name in ["riscv64-unknown-elf-gcc", "riscv32-unknown-elf-gcc"] {
        if Command::new(name)
            .arg("--version")
            .output()
            .is_ok_and(|o| o.status.success())
        {
            return Some(PathBuf::from(name));
        }
        let p = Path::new("/opt/riscv/bin").join(name);
        if p.exists() {
            return Some(p);
        }
    }
    None
}
