//! Eos demo programs, run end-to-end on the Oracle ISS over the full Snake SoC.
//!
//! The `#[test]` functions are generated by `build.rs`, which cross-compiles the
//! Eos `bin/` demos for `riscv32i-unknown-none-elf` (one ELF per demo) and emits
//! a `run_demo(...)` call per demo below via `include!`. If the `Eos/` submodule
//! or the rustc target is unavailable, the generated file is empty and this
//! binary runs zero tests.
//!
//! Each demo is self-checking: it computes a result, verifies it against a known
//! reference, and either falls through to the runtime's implicit `halt(0)` (pass)
//! or `panic!`s, which the runtime reports and turns into `halt(1)` (fail). So
//! the harness only needs to assert `exit_code == 0`; the demo's own console
//! output (captured off the UART) is attached on failure and printed under
//! `--nocapture` for inspection.

#![allow(dead_code, unused_imports)]

use std::cell::RefCell;
use std::io::{self, Write};
use std::rc::Rc;

use iss_core::{load_elf, Core, Soc, SocBuilder};

/// Step bound — generous; a passing demo halts in far fewer. Catches a runaway
/// (e.g. a demo that blocks on UART RX) instead of hanging `cargo test`.
const MAX_STEPS: usize = 200_000_000;

/// A `Write` sink that appends bytes to a shared buffer, letting the test read
/// back the UART output after the run.
struct SharedSink(Rc<RefCell<Vec<u8>>>);

impl Write for SharedSink {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        self.0.borrow_mut().extend_from_slice(buf);
        Ok(buf.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

/// Load `elf_path` onto a freshly-wired Snake SoC (BootROM + CLINT + UART +
/// IRQ-agg + DRAM), run it to halt, and assert a clean exit (`a0 == 0`). On any
/// failure the captured UART output is folded into the panic message; on success
/// it is printed so `cargo test -- --nocapture` shows each demo's console output.
fn run_demo(elf_path: &str, name: &str) {
    let captured = Rc::new(RefCell::new(Vec::<u8>::new()));
    let soc: Soc = SocBuilder::new()
        .uart_tx(Box::new(SharedSink(captured.clone())))
        .build()
        .unwrap_or_else(|e| panic!("{name}: failed to wire SoC: {e:?}"));
    let mut map = soc.map;

    let entry =
        load_elf(&mut map, elf_path).unwrap_or_else(|e| panic!("{name}: failed to load ELF: {e}"));

    let mut core = Core::new(map);
    core.state_mut().pc = entry;

    let result = core.run_until_halt_max(MAX_STEPS, |_pkt| {});
    let output = String::from_utf8_lossy(&captured.borrow()).into_owned();

    match result {
        Ok(halt) if halt.exit_code == 0 => {
            // Surface the demo's own console output (visible under --nocapture).
            print!("--- {name} UART output ---\n{output}");
        }
        Ok(halt) => panic!(
            "{name}: FAILED (halt {:?}, exit {}). UART output:\n{output}",
            halt.kind, halt.exit_code
        ),
        Err(steps) => {
            panic!("{name}: did not halt within {steps} steps. UART output:\n{output}")
        }
    }
}

include!(concat!(env!("OUT_DIR"), "/eos_demos_generated.rs"));
