//! Eos demo programs, run end-to-end on the Oracle ISS over the full Snake SoC.
//!
//! The `#[test]` functions are generated by `build.rs`, which cross-compiles the
//! Eos `bin/` demos for `riscv32i-unknown-none-elf` (one ELF per demo) and emits
//! a `run_demo(...)` call per demo below via `include!`. If the `Eos/` submodule
//! or the rustc target is unavailable, the generated file is empty and this
//! binary runs zero tests.
//!
//! Each demo is self-checking: it computes a result, verifies it against a known
//! reference, and either falls through to the runtime's implicit `halt(0)` (pass)
//! or `panic!`s, which the runtime reports and turns into `halt(1)` (fail). So
//! the harness only needs to assert `exit_code == 0`; the demo's own console
//! output (captured off the UART) is attached on failure and printed under
//! `--nocapture` for inspection.

#![allow(dead_code, unused_imports)]

use std::cell::RefCell;
use std::io::{self, Write};
use std::rc::Rc;

use hermes::terminal::QueuedBytes;
use iss_core::{load_elf, Core, Soc, SocBuilder};

/// Step bound — generous; a passing demo halts in far fewer. Catches a runaway
/// (e.g. a demo that blocks on UART RX) instead of hanging `cargo test`.
const MAX_STEPS: usize = 200_000_000;

/// A `Write` sink that appends bytes to a shared buffer, letting the test read
/// back the UART output after the run.
struct SharedSink(Rc<RefCell<Vec<u8>>>);

impl Write for SharedSink {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        self.0.borrow_mut().extend_from_slice(buf);
        Ok(buf.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

/// Load `elf_path` onto a freshly-wired Snake SoC (BootROM + CLINT + UART +
/// IRQ-agg + DRAM), run it to halt, and assert a clean exit (`a0 == 0`). On any
/// failure the captured UART output is folded into the panic message; on success
/// it is printed so `cargo test -- --nocapture` shows each demo's console output.
fn run_demo(elf_path: &str, name: &str) {
    let captured = Rc::new(RefCell::new(Vec::<u8>::new()));
    let soc: Soc = SocBuilder::new()
        .uart_tx(Box::new(SharedSink(captured.clone())))
        .build()
        .unwrap_or_else(|e| panic!("{name}: failed to wire SoC: {e:?}"));
    let mut map = soc.map;

    let entry =
        load_elf(&mut map, elf_path).unwrap_or_else(|e| panic!("{name}: failed to load ELF: {e}"));

    let mut core = Core::new(map);
    core.state_mut().pc = entry;

    let result = core.run_until_halt_max(MAX_STEPS, |_pkt| {});
    let output = String::from_utf8_lossy(&captured.borrow()).into_owned();

    match result {
        Ok(halt) if halt.exit_code == 0 => {
            // Surface the demo's own console output (visible under --nocapture).
            print!("--- {name} UART output ---\n{output}");
        }
        Ok(halt) => panic!(
            "{name}: FAILED (halt {:?}, exit {}). UART output:\n{output}",
            halt.kind, halt.exit_code
        ),
        Err(steps) => {
            panic!("{name}: did not halt within {steps} steps. UART output:\n{output}")
        }
    }
}

/// Like [`run_demo`], but feeds a scripted byte sequence to the UART RX path
/// and ticks the SoC between instructions so those bytes actually arrive.
///
/// The other demos run the core straight through, but an input demo busy-waits
/// in `getchar()` until `STATUS.RX_VALID` is set — and the UART only latches a
/// byte from its `ByteSource` on `tick()`. So here we single-step the core and
/// tick the SoC each step (the ticker shares the same device handles as the
/// bus). Asserts a clean halt and that every string in `expect` appears in the
/// captured UART output.
fn run_demo_with_input(elf_path: &str, name: &str, input: &[u8], expect: &[&str]) {
    let captured = Rc::new(RefCell::new(Vec::<u8>::new()));
    let soc: Soc = SocBuilder::new()
        .uart_tx(Box::new(SharedSink(captured.clone())))
        .uart_rx(Box::new(QueuedBytes::new(input.iter().copied())))
        .build()
        .unwrap_or_else(|e| panic!("{name}: failed to wire SoC: {e:?}"));
    // Keep the ticker and the CLINT/IRQ handles: the ticker shares the device
    // handles with `map`, and the handles let us bridge the interrupt wires
    // into the core so RX is delivered as a machine-external interrupt.
    let Soc {
        mut map,
        ticker,
        clint,
        irq,
        ..
    } = soc;

    let entry =
        load_elf(&mut map, elf_path).unwrap_or_else(|e| panic!("{name}: failed to load ELF: {e}"));

    let mut core = Core::new(map);
    core.state_mut().pc = entry;

    let mut halt = None;
    for _ in 0..MAX_STEPS {
        let pkt = core.step();
        if let Some(h) = pkt.halt {
            halt = Some(h);
            break;
        }
        ticker.tick_all(); // advance devices: UART latches a byte, IRQ latches its edge
                           // Bridge the device interrupt wires into the core's `mip` so the guest's
                           // RX interrupt fires on the next step (UART RX is interrupt-driven now).
        core.csrs_mut().set_wires(
            clint.borrow().msip(),
            clint.borrow().mtip(),
            irq.borrow().meip(),
        );
    }
    let output = String::from_utf8_lossy(&captured.borrow()).into_owned();

    match halt {
        Some(h) if h.exit_code == 0 => {
            for needle in expect {
                assert!(
                    output.contains(needle),
                    "{name}: expected {needle:?} in UART output:\n{output}"
                );
            }
            print!("--- {name} UART output ---\n{output}");
        }
        Some(h) => panic!(
            "{name}: FAILED (halt {:?}, exit {}). UART output:\n{output}",
            h.kind, h.exit_code
        ),
        None => panic!("{name}: did not halt within {MAX_STEPS} steps. UART output:\n{output}"),
    }
}

/// The Snake game, driven entirely over UART RX. Steers right ×3, up ×2,
/// left ×4 — eating all three foods — then quits. A score of 3 with a `quit`
/// status is only reachable if every scripted keystroke was received and acted
/// on, so this is the end-to-end proof that the RX path works. (If RX were
/// broken, `getchar()` would spin and the run would hit the step bound.)
#[test]
fn eos_snake() {
    let elf = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/Eos/target/riscv32i-unknown-none-elf/release/snake"
    );
    if !std::path::Path::new(elf).exists() {
        eprintln!("eos_snake: snake ELF not built (Eos cross-build unavailable); skipping");
        return;
    }
    run_demo_with_input(
        elf,
        "snake",
        b"dddwwaaaaq",
        &["score=3", "status=quit", "PASS snake"],
    );
}

/// Path to a built Eos demo ELF, or `None` if the cross-build was unavailable.
fn eos_elf(name: &str) -> Option<String> {
    let path = format!(
        "{}/Eos/target/riscv32i-unknown-none-elf/release/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    std::path::Path::new(&path).exists().then_some(path)
}

/// Real-time Snake, quit path: feeding `q` must end the game cleanly. With the
/// instruction-bound `mtime` of the test harness the snake never reaches its
/// auto-advance threshold before the keystroke arrives, so this isolates the
/// RX + quit behaviour. Proves the non-blocking `try_getchar()` loop receives
/// input and halts.
#[test]
fn eos_snake_rt_quit() {
    let Some(elf) = eos_elf("snake_rt") else {
        eprintln!("eos_snake_rt_quit: snake_rt ELF not built; skipping");
        return;
    };
    run_demo_with_input(&elf, "snake_rt", b"q", &["status=quit", "PASS snake-rt"]);
}

/// Real-time Snake, timer path: with no input the snake auto-advances on the
/// CLINT timer (here driven by the harness's per-step tick) straight into the
/// right wall and dies. Proves the timer-gated advance, render, collision, and
/// halt path without depending on any wall-clock timing.
#[test]
fn eos_snake_rt_timer() {
    let Some(elf) = eos_elf("snake_rt") else {
        eprintln!("eos_snake_rt_timer: snake_rt ELF not built; skipping");
        return;
    };
    run_demo_with_input(&elf, "snake_rt", b"", &["status=dead", "PASS snake-rt"]);
}

include!(concat!(env!("OUT_DIR"), "/eos_demos_generated.rs"));
