//! Official `riscv-tests` ISA suite, run on the Oracle ISS.
//!
//! The actual `#[test]` functions are generated by `build.rs`, which cross-
//! compiles each upstream `.S` test against the EBREAK `snake` env (one ELF per
//! test) and emits a `run_one(...)` call per test below via `include!`. If the
//! RISC-V toolchain or the submodules are unavailable, the generated file is
//! empty and this binary simply runs zero tests.
//!
//! Pass/fail convention (snake env): the test ends in `EBREAK` with `a0`
//! holding the exit code — `0` = pass, an odd value `(n << 1) | 1` = failure at
//! test case `n`. The ISS surfaces this as `HaltKind::Voluntary` with
//! `exit_code = a0 & 0xFF`.

#![allow(dead_code, unused_imports)]

use std::cell::RefCell;
use std::rc::Rc;

use iss_core::{load_elf, Core, Dram, DramModel, HaltKind, MemoryMap};

/// DRAM base/entry for the snake env (see `riscv-test-env/snake/link.ld`).
const DRAM_BASE: u32 = 0x8000_0000;
/// 4 MiB comfortably covers every rv32ui/rv32mi image and its data.
const DRAM_SIZE: u32 = 4 * 1024 * 1024;
/// Upper bound on retired steps — catches a test that never reaches EBREAK.
const MAX_STEPS: usize = 2_000_000;

/// Load one test ELF into a fresh DRAM-backed `MemoryMap`, run it to halt, and
/// assert it signalled pass (`exit_code == 0`). Panics with a decoded reason on
/// any failure so `cargo test` reports the failing test case number.
fn run_one(elf_path: &str, name: &str) {
    let dram = Rc::new(RefCell::new(
        Dram::new(DRAM_SIZE, DramModel::Ideal).unwrap(),
    ));
    let mut map = MemoryMap::new();
    map.add_device(DRAM_BASE, DRAM_SIZE, dram).unwrap();

    let entry =
        load_elf(&mut map, elf_path).unwrap_or_else(|e| panic!("{name}: failed to load ELF: {e}"));

    let mut core = Core::new(map);
    core.state_mut().pc = entry;

    match core.run_until_halt_max(MAX_STEPS, |_pkt| {}) {
        Ok(halt) if halt.exit_code == 0 => {} // pass
        Ok(halt) => match halt.kind {
            HaltKind::Voluntary { .. } => panic!(
                "{name}: FAILED at test case #{} (exit {})",
                halt.exit_code >> 1,
                halt.exit_code
            ),
            other => panic!(
                "{name}: halted involuntarily: {other:?} (exit {})",
                halt.exit_code
            ),
        },
        Err(steps) => panic!("{name}: did not halt within {steps} steps"),
    }
}

include!(concat!(env!("OUT_DIR"), "/riscv_tests_generated.rs"));
